pkg/driver/steinel/hpd/config/root.go, pkg/driver/steinel/hpd/driver.go, pkg/driver/steinel/hpd/trait_airquality.go, pkg/driver/steinel/hpd/trait_occupancy.go, pkg/driver/steinel/hpd/trait_temphumidity.go, pkg/driver/steinel/hpd/udmi.go, pkg/driver/steinel/hpd/udmi_test.go
Exports the airquality, temphumidty and occupancy traits via UDMI
=> driver/steinel/hpd: implement udmi trait for steinel hpd

ui/conductor/src/util/router.js
=> opsui/overview: change encode to decode when comparing route path with item title

ui/conductor/src/routes/ops/overview/pages/widgets/energyAndDemand/useMeterHistory.js
=> opsui/overview: remove leftover console.log

ui/conductor/src/routes/ops/overview/pages/widgets/environmental/EnvironmentalCard.vue
=> opsui/overview: centering "external temperature" text in environmental widget

ui/conductor/src/routes/ops/notifications/Notifications.vue
=> opsui/notifications: fix computed not writable error when changing zone

ui/conductor/src/api/sc/traits/light.js
=> opsui/traits: add describeBrightness api support for future lighting preset fetching

ui/conductor/src/routes/devices/components/DeviceCell.vue, ui/conductor/src/traits/access/AccessAttemptCell.vue, ui/conductor/src/traits/airTemperature/AirTemperatureCell.vue, ui/conductor/src/traits/electricDemand/ElectricDemandCell.vue, ui/conductor/src/traits/emergency/EmergencyCell.vue, ui/conductor/src/traits/enterLeave/EnterLeaveEventCell.vue, ui/conductor/src/traits/lighting/LightCell.vue, ui/conductor/src/traits/meter/MeterCell.vue, ui/conductor/src/traits/occupancy/OccupancyCell.vue, ui/conductor/src/traits/openClosed/OpenClosedCell.vue, ui/conductor/src/traits/status/StatusLogCell.vue
=> opsui/traits: move statusAlert component to traitCell

pkg/driver/mock/driver.go
=> driver/mock: add fixed presets to the mock lighting driver

pkg/zone/feature/lighting/group.go, pkg/zone/feature/lighting/group_test.go, pkg/zone/feature/lighting/lighting.go
Have zones implement the LightInfo api backed by the members of the zone - if they support it.
Jira: SC-463
=> zone/lighting: add preset support

ui/conductor/src/traits/lighting/LightCard.vue, ui/conductor/src/traits/lighting/useLightingTrait.js
=> opsui/lightingTrait: tidy up LightCard component template and logic

pkg/driver/xovis/config.go, pkg/driver/xovis/driver.go, pkg/driver/xovis/trait_enterleave.go, pkg/driver/xovis/trait_occupancy.go, pkg/driver/xovis/udmi.go, pkg/driver/xovis/udmi_test.go
Adds the UDMI trait to the xovis driver. 
Similair pattern to the steinel hpd udmi implementation
=> driver/xovis: Add udmi trait to xovis driver

pkg/driver/proxy/driver.go
Todo removed and added as task for history -> https://vanti.atlassian.net/browse/SC-465?atlOrigin=eyJpIjoiZGIxZDgwZTdmMjMxNDY1YzhhNTYzOTY4NTBlMTIyODQiLCJwIjoiaiJ9
=> driver/proxy: add support to proxy info

ui/conductor/src/api/ui/alerts.js
=> opsui/alertsAPI: fix wrong param in setProperties

ui/conductor/src/api/ui/alerts.js, ui/conductor/src/routes/ops/notifications/Notifications.vue
This PR contains an expansion panel within the Notifications.vue component, which shows/hides a form for a new notification entry.
The entry includes: description, severity, floor and zone values.
Jira: SC-467
=> opsui/notifications: added ability to add manually specified notifications

ui/conductor/src/api/ui/alerts.js
=> opsui/alertsAPI: change alertQueryFromObject setProperty's prop to match query

cmd/tools/sample-tenant/main.go
Before it was doing the http request to get the token itself, now it's using the clientcredentials package and setting the auth on the grpc.ClientConn. Much more idiomatic.
=> cmd/tools: update sample-tenant to use go packages for oauth

cmd/tools/test-notificationsemail/main.go, pkg/auto/allautos/factory.go, pkg/auto/notificationsemail/auto.go, pkg/auto/notificationsemail/config/root.go, pkg/auto/notificationsemail/email.go, pkg/gentrait/alert/model.go, pkg/gentrait/alert/model_server.go
This auto is more to tick a box on a spec than provide a desired feature. I expect this auto to be modifed or even removed when the notifications/alert system has been redesigned.
=> auto/notificationsemail: add auto to send email with previous months notifications as CSV attachment

ui/conductor/src/components/VSwitch2.vue, ui/conductor/src/components/filter/BooleanChoiceListItem.vue, ui/conductor/src/components/filter/BooleanChooserChip.vue, ui/conductor/src/components/filter/FilterBtn.vue, ui/conductor/src/components/filter/FilterChoiceChips.vue, ui/conductor/src/components/filter/FilterChooser.vue, ui/conductor/src/components/filter/ListChooser.vue, ui/conductor/src/components/filter/MenuChooserChip.vue, ui/conductor/src/components/filter/PageChoiceListItem.vue, ui/conductor/src/components/filter/PageChooser.vue, ui/conductor/src/components/filter/RangeChooser.vue, ui/conductor/src/components/filter/choiceRange.js, ui/conductor/src/components/filter/filterCtx.js, ui/conductor/src/components/filter/pageCtx.js, ui/conductor/src/composables/visibility.js, ui/conductor/src/routes/ops/notifications/Notifications.vue, ui/conductor/src/routes/ops/notifications/notifications.js, ui/conductor/src/traits/airQuality/airQuality.js
Completely redesigned the filter and its functionality.
Improved flexibility, added extra logic and missing functionality.
> Note: at the moment it is only being used on the Notifications page.
Jira: SC-3, SC-461
=> opsui/notifications: upgraded and expanded filtering of alerts on the notifications page

ui/conductor/src/traits/light/LightCard.vue, ui/conductor/src/traits/light/light.js
Highlights the currently selected lighting preset with the primary colour
=> ui: Highlight selected light preset

pkg/system/history/page.go, pkg/system/history/page_test.go
=> system/history: fix nil dereference when parsing page token proto

pkg/system/proxy/factory.go
They were lacking which made understanding the system and package hard.
I thought I'd do this before tackling upgrading the package to support dynamic API proxying.
=> proxy: update/add go docs

pkg/system/proxy/factory.go, pkg/system/proxy/internal/test/proxy_test.go, pkg/system/proxy/internal/test/shared/args.go, pkg/system/proxy/internal/test/testdata/ac1/system.conf.json, pkg/system/proxy/internal/test/testdata/ac2/system.conf.json, pkg/system/proxy/internal/test/testdata/gw1/system.conf.json, pkg/system/proxy/internal/test/testdata/gw2/system.conf.json, pkg/system/proxy/internal/test/testdata/hub/system.conf.json
These changes improve the testing of the proxy package, hopefully removing the flakyness from our tests.
I've included some general improvements to the code that were useful in troubleshooting the problem, these seemed generally useful so I left them in.
Fixed: SC-596
=> system/proxy: improved proxy testing

.github/workflows/ui.yml, ui/yarn.lock
.github/workflows: Add CI workflow and step to verify `yarn.lock` file doesn't contain references to private `nexus.vanti.co.uk` repositories
=> Feature/sc 613 check yarn.lock ci

pkg/driver/bacnet/merge/air_quality.go, pkg/driver/bacnet/merge/trait.go
Adds air quality support to the bacnet driver, mostly just copy pasted from air temperature
=> driver/bacnet: add air quality sensor support

pkg/driver/steinel/hpd/driver.go, pkg/driver/steinel/hpd/poller.go, pkg/driver/steinel/hpd/trait_airquality.go, pkg/driver/steinel/hpd/trait_occupancy.go, pkg/driver/steinel/hpd/trait_temphumidity.go, pkg/driver/steinel/hpd/trait_temphumidity_test.go
Use a single polling loop for all `GetUpdate()` REST API `GET` calls in steinel driver
=> [SC-484] feat: refactor steinel driver to use 1 polling loop

ui/conductor/src/traits/electricDemand/ElectricDemandCard.vue, ui/conductor/src/traits/electricDemand/electric.js
=> ui/ops: optionally hide zero electric values

pkg/zone/area/area.go, pkg/zone/feature/openclose/config/root.go, pkg/zone/feature/openclose/group.go, pkg/zone/feature/openclose/group_test.go, pkg/zone/feature/openclose/openclose.go
=> zone: add openclose trait support to zones

internal/manage/devices/server.go
=> devices: fix nil pointer crash with bad request inputs

ui/conductor/package.json, ui/keycloak-login-prototype/package.json, ui/ui-gen/package.json, ui/yarn.lock
Upgrade a few dependencies for the OPS UI. I had issues when building the latest main Ops UI from arg-ocw, updating a few dependencies fixed the issue.
=> Update vue, pinia & sc-api-grpc-web

ui/ops/src/composables/devices.js, ui/ops/src/routes/ops/notifications/NotificationsTable.vue
It's not ideal that we need to make this change in so many places, but that's how it is now. We can refactor in another change if we need to.
Fixes SC-977
=> ui/ops: for floors, sort 10 after 2

docs/auth-use-cases.md, docs/authn-schedule.md, docs/authz.md, docs/client-credentials.md, docs/design/authorization-model.md, docs/new-authz-model.md, docs/permissions-scheme.md
Add file `docs/design/authorization-model.md` to describe how the new authentication model will work.
No code changes to implement this - these will come in separate PRs.
Annotate other documents to indicate they haven't been updated yet.
=> docs: Document new authorization model

scripts/gen-proto.sh
Support both versions of router/wrapper -> https://github.com/smart-core-os/sc-golang/pull/18
=> scripts: support new router/wrapper plugin output

pkg/driver/bacnet/rpc/gen-proto.sh
Add a gen-proto script for the bacnet rpc and support both versions of the wrapper & router plugins
=> scripts: add gen proto script for bacnet rpc

ui/ops/src/dynamic/widgets/power-history/PowerHistoryGraph.vue, ui/ops/src/dynamic/widgets/power-history/useMeterHistory.js
Previously it was computing the CSV content locally and providing the download that way. Now its reusing the DevicesApi DownloadLink feature to get all meter readings for the displayed period.
Blocked on #369, but can be reviewed now as the general approach won't change. I'll change the base once that PR lands
=> ui/ops/power: use devices download api for the power history chart

cmd/tools/client-securityevent/main.go, pkg/driver/alldrivers/factory.go, pkg/driver/gallagher/README.md, pkg/driver/gallagher/alarms.go, pkg/driver/gallagher/cardholders.go, pkg/driver/gallagher/client.go, pkg/driver/gallagher/config/example.json, pkg/driver/gallagher/config/root.go, pkg/driver/gallagher/doors.go, pkg/driver/gallagher/driver.go, pkg/driver/gallagher/occupancy.go, pkg/gentrait/securityevent/model.go
This promotes the gallagher driver from the ocw project to sc-bos as it now needed for other projects.
I have edited the readme to remove the project specific stuff and also added an example.json file to help people use this driver in their projects.
=> driver/gallagher: add gallagher driver

pkg/driver/bacnet/merge/energy_storage.go, pkg/driver/bacnet/merge/trait.go
adds support for energy storage devices communicating via bacnet
=> drivers/bacnet: add energy storage trait support

pkg/auto/allautos/factory.go, pkg/auto/resetbrightness/auto.go, pkg/auto/resetbrightness/config/root.go
See the package docs for the auto for details.
This auto can be used to turn the lights off in a room a bit after someone has turned them on.
I have tested this using the vanti-ugs example and different configuration options.
=> auto/resetbrightness: add an auto to reset brightness after a delay

pkg/driver/mock/auto/Meter.go, pkg/driver/mock/auto/OccupancySensor.go, pkg/driver/mock/auto/electric.go, pkg/driver/mock/auto/rand.go, pkg/driver/mock/scale/time.go
Now electric, meter, and occupancy values will change based on the working day.
Also includes more realistic meter calculations based on kWh instead of random increments.
=> driver/mock: add time of day scaling for random values

cmd/tools/bacnet-multi-comm-test/main.go, cmd/tools/dbadd-alerts/main.go, cmd/tools/export-traits/main.go, cmd/tools/test-notificationsemail/main.go, cmd/tools/test-statusemail/main.go, internal/manage/devices/server_test.go, internal/router/stream.go, internal/util/pass/compare_test.go, pkg/auto/feature/power.go, pkg/driver/bacnet/comm/value.go, pkg/driver/xovis/count.go, pkg/gentrait/historypb/page.go, pkg/gentrait/securityevent/model.go, pkg/manage/enrollment/server.go, pkg/minibus/bus_test.go, pkg/node/metadata.go, pkg/node/node.go, pkg/task/service/map.go, pkg/util/once/retry_test.go, pkg/zone/feature/run/parallel.go
Places found with: `for (\w+) := 0; \1 < ([\w\d]+); \1\+\+ \{`
=> all: use range-over-int where we can

internal/router/stream_test.go
Our wrap.ServerToClient func handles unary api calls inline, but streaming calls pace the handler invocation in a goroutine. This inadvertently mimics real network calls by making it non-deterministic whether a Pull right before an Update will reach the server in that order.
The StreamHandler test was relying on these calls to reach the server in the same order they were called by the client.
The fix here is to make sure the stream is active before relying on any ordering of calls.
=> internal/router: fix a flaky test caused by racing between stream and unary api calls

pkg/system/gateway/factory.go, pkg/system/gateway/scan.go
Change log field names and order to make reading the logs easier.
=> system/gateway: make logging more consistent

pkg/gentrait/serviceticketpb/model.go, pkg/gentrait/serviceticketpb/model_server.go, pkg/gentrait/serviceticketpb/serviceticket.go, pkg/node/alltraits/services.go
add the model and model server. also add pb suffix to package name
=> traits: add model server for ServiceTicket

ui/ops/src/traits/electricDemand/ElectricDemandCard.vue, ui/ops/src/traits/electricDemand/electric.js
=> ops: add current to the electric sidebar card

example/config/vanti-ugs/app.conf.json, pkg/driver/mock/auto/energystorage.go, pkg/driver/mock/auto/rand.go, pkg/driver/mock/driver.go, ui/ops/src/api/sc/traits/energy-storage.js, ui/ops/src/routes/devices/components/DeviceCell.vue, ui/ops/src/routes/devices/components/DeviceSideBarContent.vue, ui/ops/src/traits/energyStorage/EnergyStorageCard.vue, ui/ops/src/traits/energyStorage/EnergyStorageCell.vue, ui/ops/src/traits/energyStorage/WithEnergyStorage.vue, ui/ops/src/traits/energyStorage/energyStorage.js, ui/ops/src/traits/traits.js
Add a mock simulation, example devices, and ui components to show energy storage devices.
I've included all the changes in one pr so that they can be easily tested.
=> all: add energy storage trait support
