vanti-dev/sc-bos

- ui/conductor/src/routes/ops/overview/pages/widgets/energyAndDemand/EnergyGraph.vue
- ui/conductor/src/routes/ops/overview/pages/widgets/energyAndDemand/EnergyGraphOptionsMenu.vue
- ui/conductor/src/routes/ops/overview/pages/widgets/energyAndDemand/useMeterHistory.js
This PR adds an app functionality, which gives the user the ability to **export raw meter readings in a CSV format**.
The change comes with a menu option on _Power/Energy Consumption widget -> Options button_, and is called **Export CSV...**.
When the user clicks this option, it triggers the following process:
**Existing records (raw meter readings)** are being grouped into span groups - where the `span` is being provided **by the active duration option** -, then **the last reading of each span groups** are being collected and processed for export into a CSV format, using the existing `downloadCSV` utility.
Jira: PRJ-117
> opsui/overview: export `raw meter readings` in CSV format

- ui/conductor/src/routes/ops/overview/pages/DynamicAreasOverview.vue
While clicking between `overview-children` on the navigation bar, I've noticed in a console the following error:
`[Vue warn]: You may have an infinite update loop in a component render function.`
The cause of this error has been identified, and is now fixed.
Jira: PRJ-117
> opsui/overview: fix an infinite component render loop

- ui/conductor/src/routes/ops/notifications/Notifications.vue
- ui/conductor/src/routes/ops/overview/pages/DynamicAreasOverview.vue
- ui/conductor/src/routes/ops/overview/pages/components/LeftColumn.vue
- ui/conductor/src/routes/ops/overview/pages/components/RightColumn.vue
- ui/conductor/src/routes/ops/overview/pages/widgets/environmental/EnvironmentalCard.vue
- ui/conductor/src/routes/ops/overview/pages/widgets/occupancy/PresenceCard.vue
To make the `overview-child design` look more similar to the building overview page design, I've reordered the widgets we display on the page. Also contains label change _(on presence widget)_ and addition _(on notifications page)_
Jira: N/A
> opsui/overview: reorder widgets on overview-child path

- ui/conductor/src/routes/ops/overview/route.js
With the addition of the `notifications` table, we require a different layout template - so we can show/hide the past 10 notification / device details on the table row click.
Jira: PRJ-117
> opsui/overview: change `ops/overview` page template to have right `sidebar`

- ui/conductor/src/routes/ops/overview/pages/widgets/environmental/EnvironmentalCard.vue
From this:
To this:
Jira: PRJ-117
> opsui/overview: fix `environmental` widget gauge alignment

- ui/conductor/src/routes/ops/overview/pages/widgets/energyAndDemand/useMeterHistory.js
We've noticed, that the energy graph doesn't trigger a fetch action when the active overview-child path changes. This has been fixed.
Jira: PRJ-117
> opsui/overview: fix `energy graph` update on navigation

- pkg/system/alerts/pgxalerts/pgx.go
In the case where there are lots of alerts that share the same create_time we were returning the same page each time, even with a pageToken specified. Now we don't do that.
> alerts/pgx: fix pagination in cases where create_time is the same

- ui/conductor/src/routes/ops/notifications/Notifications.vue
- ui/conductor/src/routes/ops/notifications/useAlertsApi.js
- ui/conductor/src/routes/ops/overview/pages/components/LeftColumn.vue
- ui/conductor/src/util/downloadCSV.js
As per a client request, now we have the ability to export notifications in CSV format.
The functionality is available for `all` _(under `Notifications` nav option)_ or `per overview page` _(when selecting an available sub-overview page within `Building Overview`)_.
Jira: PRJ-115
> opsui/notifications: add ability to export `Notifications` into CSV

- ui/conductor/src/routes/ops/overview/pages/widgets/occupancy/PresenceCard.vue
When the `Last updated` string was short (displayed `now`), it positioned next to the `presence state` text. This is now fixed with `flex-column` class.
Jira: N/A
> opsui/overview: fix `presence` widget's style

- pkg/zone/feature/lighting/config/root.go
- pkg/zone/feature/lighting/lighting.go
Before configuring lightGroups like `"lightGroups:{"foo": [...]}` would announce a device like `{base}/lights/foo`. This bucks the convention of all other zone features and reduced the utility of it.
This change it technically breaking but I found no uses of `"lightGroups"` outside example config in all our repos so I think we'll be ok.
> zone/lights!: don't put `/lights/` between the base and key name for lightGroups

- ui/conductor/src/routes/router.js
- ui/conductor/src/stores/page.js
The right hand sidebar stayed on screen with the previously selected data when we've navigated away from a page. This is fixed.
Jira: N/A
> opsui/router: reset sidebar display on nav change

- ui/conductor/src/routes/ops/notifications/Filters.vue
- ui/conductor/src/routes/ops/notifications/Notifications.vue
Refactored the _Filter.vue_ component to use a v-for loop when creating dropdown selectors and added a new selector option for listing _**All/Acknowledged/Unacknowledged**_ notifications.
Jira: SC-4
> opsui/notifications: allow showing only unacknowledged alerts

- pkg/auto/udmi/config/mqtt.go
The password and password file options were configurable, but nothing was using them. This PR just sets the password in the broker options if one was provided
> auto/udmi/config: add set password to mqtt broker opts

- ui/conductor/src/traits/lighting/LightCard.vue
This PR contains a fix for an issue, where long preset button text was overflowing to each side of the button.
This has been fixed with truncating the labels.
Jira: SC-464
> opsui/lightCard: truncate overflowing preset titles

- ui/conductor/src/routes/ops/OpsNav.vue
- ui/conductor/src/routes/ops/notifications/alertMetadata.js
- ui/conductor/src/routes/ops/notifications/useAlertsApi.js
> opsui/OpsNav: Eliminate pullAlertMetadata error snackbar

- pkg/system/proxy/factory.go
:D can now access the hub's AlertAdminApi from the Edge Gateway
I have created this task SC-469  to re-undo this once we have a better way
> expose alert admin api on hub

- pkg/driver/proxy/config/root.go
- pkg/driver/proxy/driver.go
If the list of children is not present of empty in config then we announce all children of the parent node.
We currently list the traits explicitly too. This could be avoided by calling the meta data trait on the child device.
> Add explicit child devices in proxy driver

- internal/auth/tenant/token_server.go
Without this the clientcredentials package fails to parse the response, assuming it's a form body and not json.
> auth: add missing Content-Type header to client credential token responses

- cmd/tools/test-meteremail/main.go
- pkg/auto/meteremail/auto.go
- pkg/auto/meteremail/config/root.go
Removes hardcoded backoffStart, backoffMax and noRetries when sending meteremails and allows these to be configured from config. If not present in config then default values are set.
Fixes test-meteremail program & adds new timing config to test program
> auto/meteremail: add configurable retries & backoff timing 

- cmd/tools/test-meteremail/main.go
- pkg/auto/meteremail/auto.go
- pkg/auto/meteremail/config/root.go
- pkg/auto/meteremail/template.go
Removes the hardcoded OCW from sc-bos auto & adds template args to config.
https://vanti.youtrack.cloud/issue/SC-479/remove-client-string-from-meteremail-auto-body
> auto/meteremail: make email title configurable

- pkg/auth/policy/default/smartcore.bos.driver.dali.DaliApi.rego
- pkg/auth/policy/default/test_general.rego
Adjust the OPA policies to grant access to these methods if you are an operator.
Issue: SC-540
> auth: allow operators to start/stop lighting tests

- .github/workflows/build-sc-bos.yml
- .github/workflows/docker-package.yml
Build sc-bos and the sc-bos container image for arm64 Linux.
Good for testing on Macs.
> SC-547: build container with arm64 support

- .github/workflows/docker-package.yml
- Dockerfile
Multiarch containers are only uploaded correctly by docker/build-push-action if they are all done together.
If uploaded in multiple steps, the newest will overwrite the oldest and the image is not multiarch.
Tweak Dockerfile to look in arch-specific directory for copying in build artifacts. Modify action to extract to the correct directories.
Fixes the code introduced in #242
> actions: fix multiarch container builds

- .github/workflows/docker-package.yml
I realised I can test this before it's in main and I promise [it works now](https://github.com/vanti-dev/sc-bos/pkgs/container/sc-bos/226947343?tag=v0.0.0-test-multiarch)
> actions: use buildx to enable multiplatform builds

- .github/docker/prebuilt.Dockerfile
- .github/workflows/docker-package.yml
- Dockerfile
- ui/conductor/package.json
- ui/conductor/vite.config.js
- ui/conductor/yarn.lock
This isn't part of a ticket, but I was doing some related work on another repo and though sc-bos could benefit from the same thing.
Add a new Dockerfile which performs the build process internally, instead of copying in prebuilt artifacts. Move the old Dockerfile, and use it in the Github Action as before, so there's no behaviour change to the CI here (we could modify this later).
The new Dockerfile allows the user to simply run `docker/podman build -t sc-bos --secret=id=npmrc,src=$HOME/.npmrc .` and they will have a working sc-bos docker container. This is a smoother developer experience.
Multi-stage builds are used to ensure the final image is minimal, and doesn't contain the build tools or secrets. Cross-compilation is supported (using the `--platform` argument to `docker build`).
> Dockerfile to build sc-bos entirely

- cmd/tools/test-meteremail/main.go
- pkg/auto/meteremail/email.go
Add support to send to multiple recipients, just wrap a loop around what we already have. 
Google no longers support multiple recipients in the to header https://westoahu.hawaii.edu/it/news/googleuh-gmail-will-reject-messages-with-non-compliant-headers-beginning-april-24-2023/
> auto/meteremail: Meteremail multiple recipients

- pkg/auth/policy/grpc.go
- pkg/auth/policy/grpc_test.go
- pkg/auth/policy/policy.go
- pkg/auth/policy/rego_test.go
To correctly convert proto messages to OPA policy data we need to reliably be able to convert those messages to json.
The protojson package is a much better fit for this than the json package, which is the default used by OPA.
Unfortunately there's no easy way to hook into specific type marshalling of inputs, so we convert it before passing to the OPA evaluation.
This PR is part of the work to enable user editable config, via supporting dynamic services in the gateway/proxy.
> auth: use protojson to marshal requests into policy inputs

- pkg/task/poll.go
- pkg/task/poll_test.go
Because select is nondeterministic when multiple cases are ready, Poll/PollErr might run one time extra after the context is cancelled. This is because the ticker channel may already contain an element sent during the previous poll operation. Add an explicit check for a completed context before checking for a tick.
> SC-606: Fix case of calling stop in task.PollErr and more tasks running

- .github/workflows/build-sc-bos.yml
- .github/workflows/go-test.yml
We use some outdated actions, which run on Node 16. This produces a deprecation warning in Github.
Upgrade versions to latest to remove this warning.
> Update actions to stop Node version warning

- .gitignore
- pkg/auto/lights/auto_test.go
- pkg/auto/lights/patch.go
fix: order emitter bus elements to prevent rare test failure condition
`pkg/auto/lights/auto_test.go` -> the lack of ordering on the bus means some states were being played later than usual causing the `waitForState()` call on line 158 to race ahead to the next assertion before the **_**actual**_** call to updateBrightness had been issued.
fix: move config changes up to mitigate risk of config not yet being applied before states are processed
sometimes, in very rare cases, the config passed from the test isn't applied before calls to `setOccupancy` are issued, meaning the timestamps look at real time instead of unix zero time. There is still a very very low risk this can happen, but trying to sync the config with the first call to `setOccupancy` seemed like overkill for now.
> fix intermittent test failures

- pkg/app/appconf/store.go
- pkg/app/appconf/store_test.go
Fixes bug SC-628.
Trivial fix with tests to confirm.
> appconf: correctly handle empty type when updating service config

- pkg/app/servers_test.go
Insert this in line 49:
```go
serveErr := make(chan error, 1)
go func() {
time.Sleep(time.Second)
err := ServeHTTPS(ctx, server, time.Second, zap.NewNop())
if !errors.Is(err, context.Canceled) {
t.Error(err)
}
serveErr <- err
}()
```
and the test hangs forever due to TLS not being configured with a timeout.
> app/server: fix intermittent test failures

- pkg/driver/steinel/hpd/client.go
Fixes [SC-635](https://vanti.youtrack.cloud/issue/SC-635/Fix-breaking-change-when-communicating-with-Steinel-sensors)
Allow all the ciphers to maintain backwards and forwards compatability for our Steinel sensors
> driver/steinel: allow older TLS ciphers

- pkg/app/sysconf/config.go
- pkg/auto/azureiot/config.go
- pkg/auto/azureiot/factory.go
- pkg/auto/meteremail/auto.go
- pkg/auto/meteremail/config/root.go
- pkg/block/mdblock/md.go
- pkg/driver/airthings/config.go
- pkg/driver/airthings/driver.go
- pkg/driver/bacnet/config/root.go
- pkg/driver/bacnet/driver.go
- pkg/driver/mock/config/root.go
- pkg/driver/mock/driver.go
- pkg/zone/area/area.go
This PR adds a few config blocks to some autos and drivers as a sample for how this should be done.
The blocks aren't added to all built in services, as the block system can be updated over time when we need to. However, I feel like these are a good starting point and should make the user config editing a bit more useful.
If we find in the future that we're writing tools that update only a small part of this config we can update the blocks then.
Similarly if/when we write dedicated forms for each of the drivers to edit the config outside a json editor, we can update them then too.
Fixes SC-629
> all: add auto/driver service blocks

- .github/workflows/build-sc-bos.yml
- docs/releases.md
- ui/.npmrc
- ui/panzoom-package/package.json
- ui/ui-gen/package.json
- ui/yarn.lock
We shouldn't be referencing nexus in sc-bos now except for the check in the workflow that we aren't referencing it
> Remove references to private nexus from docs & packages

- pkg/auto/lights/auto.go
- pkg/auto/lights/auto_test.go
- pkg/auto/lights/config/root.go
- pkg/auto/lights/config/root_test.go
- pkg/auto/lights/logic_test.go
- pkg/auto/lights/patch.go
auto/lights: add tests for retrying when updateBrightness fails
I changed the constants to be part of the config.
I also added config options for retry-ability in the auto/lights package. Updated some tests to verify this.
> auto/lights: add ability to retry if updating brightness fails

- pkg/driver/bacnet/comm/value.go
- pkg/driver/bacnet/merge/emergency.go
Add the ability to set an emergency when a given bacnet point reads the configured value, intended for binary alarm states, fire alarm, water level low etc
> driver/bacnet: add configurable emergency based on point value

- pkg/node/node.go
- pkg/system/gateway/announce.go
- pkg/system/gateway/factory.go
- pkg/system/gateway/scan.go
Make logging for the gateway and node a little less 'false negative'-y, less stuttery, and more consistent.
This should help to identify actual issues with the boot process and general node/gateway/hub issues.
> node,gateway: improved logging

- pkg/driver/proxy/driver.go
- pkg/node/node.go
- pkg/node/service.go
Fix an issue that had symptoms like 'name not found' when it should exist.
The root cause was the proxy drivers `skipChild` feature not working since the reworking of the node package to support ClientConnInterface (instead of generated service wrappers/routers). The change was that metadata was always added for all names, which resulted in those named being queryable via the DevicesApi. The DevicesApi is used by both gateways and proxies, and having authoritative devices in that list (when we didn't want them) could cause unexpected issues.
In summary, when a device name was discovered in more than one place, the routing could break causing not-found issues for some apis but still have discovery work.
This change makes it possible again to announce a name without it appearing in the …
> node,proxy: fix incorrect 'owner node' when using proxy.skipChild

- go.mod
- go.sum
- pkg/driver/mock/driver.go
- pkg/driver/mock/openclose.go
- pkg/zone/feature/openclose/group.go
- pkg/zone/feature/openclose/group_test.go
We now support configuring presets for the mock driver and as part of a zone.
Fixes SC-920
> driver/mock,zone/openclose: add support for open close presets

- pkg/node/alltraits/clients.go
Add missing `*gen.HistoryAdminApiClient` `*gen.AlertApiClient` to switch.
> history: fix missing History Admin & alert API client

- internal/util/pki/ca.go
- pkg/app/controller.go
- pkg/app/sysconf/config.go
- pkg/util/netutil/ip.go
This allows more flexible hosting infrastructure, including containers accessing host systems and inter-container comms via host names
> app: allow adding to the self-signed SAN list from config

- pkg/auto/statusalerts/statusalerts.go
This fixes issues on area controllers when they try to publish alerts
> auto/statusalert: use the new client connection mechanism

- pkg/auto/lights/auto_test.go
lights/auto_test: as the model server is still running, we want lastUnoccupiedTime to resolve to -3 minutes from the start of the test existence
if we don't set StateChangeTime to this, the PIR automation logic *sometimes* resolves lastUnoccupiedTime to Unix zero.
which means the logic defaults back to the readState.AutoStartTime
since the unoccupiedOffDelay is set to 10 minutes
and now.Sub(unix 0) is 7 minutes, we get a ttl of ~3minutes whenever the test fails which we don't want.
> auto/lights: fix intermittent test failures by being stricter with stateChangeTime field

- pkg/system/hub/pgxhub/server.go
> hub/pgxhub: return the error in TestHubNode

- ui/conductor/src/components/default/NavigationDrawer.vue
When not in production mode, simulate a modern ops ui version by using `new Date()`
> ui/ops: show more modern version strings when running locally

- pkg/node/alltraits/clients.go
Missing case in NewClient lookup, fixes https://vanti.youtrack.cloud/issue/INF-280/fix-5hp-building-controller-as-hub
> fix: add hub api client to lookup

- go.mod
- go.sum
- pkg/util/pull/opts.go
- pkg/util/pull/pull.go
- pkg/util/pull/pull_test.go
pull.OrPoll (and pull.Changes) used to have an assumption that if pull and get both returned errors with codes.Unimplemented then there was no point continuing to retry the requests as this couldn't change. This assumption was violated when we implemented dynamic gRPC apis as part of the dynamic gateway work.
This change adjusts the pull functions to retry even when Unimplemented is returned.
> util/pull: retry pull even when Unimplemented

- internal/driver/settings/driver.go
- pkg/auto/history/factory.go
- pkg/auto/history/occupancysensor_test.go
- pkg/driver/airthings/driver.go
- pkg/driver/bacnet/driver.go
- pkg/driver/pestsense/driver.go
- pkg/driver/se/wiser-knx/driver.go
- pkg/driver/shelly/trv/driver.go
- pkg/driver/steinel/hpd/driver.go
- pkg/node/announce.go
- pkg/node/announce_test.go
- pkg/system/alerts/factory.go
- pkg/system/gateway/announce.go
- pkg/system/history/factory.go
- pkg/system/publications/factory.go
- pkg/zone/area/area.go
- pkg/zone/feature/access/access.go
- pkg/zone/feature/airquality/airquality.go
- pkg/zone/feature/electric/electric.go
- pkg/zone/feature/enterleave/enterleave.go
- pkg/zone/feature/enterleave/group.go
- pkg/zone/feature/hvac/hvac.go
- pkg/zone/feature/lighting/lighting.go
- pkg/zone/feature/meter/meter.go
- pkg/zone/feature/mode/mode.go
- pkg/zone/feature/occupancy/occupancy.go
- pkg/zone/feature/openclose/openclose.go
- pkg/zone/feature/status/status.go
The existing AnnounceContext is insufficient for services, because there's no way to wait for previous announcements to be undone before announcing the devices again.
Announcements are then interleaved incorrectly with undos which produces missing metadata etc.
These new types provide a way for a driver to wait for its previous announcements to be undone before it makes new ones.
> node: add AnnounceScope and ReplaceAnnouncer, deprecate AnnounceContext

- pkg/app/controller.go
- pkg/auth/policy/default/http.rego
- pkg/auth/policy/interceptor.go
- pkg/auth/policy/interceptor_test.go
- pkg/auth/policy/policy.go
- pkg/auth/policy/policy_test.go
We have an endpoint `/__/log/level` which is not auth-protected but should be.
Add HTTP support to policy.Interceptor.
Add Protocol and Path to Attributes to allow policies to access HTTP details.
Only hook up HTTP auth for the log level handler for now.
Other endpoints should have it applied, but we need to
do a comprehensive inventory of endpoints first and work out what to do with the dynamically registered endpoints.
> SC-970: add HTTP middleware to authorize access

- pkg/node/node.go
If one of the aspects of a trait was defined without any rpc methods then this service would be treated by node.Node and router.Router as non-routable. During announcement Node would attempt to register that service against the new name, causing ERROR in the logs like:
> cannot register service smartcore.traits.ElectricInfo for "my-device": service "smartcore.traits.ElectricInfo" already exists but does not support name routing
This change filters out these useless services which also can cause issues with type checking, an empty interface matches against all types so everything implements ElectricInfoClient (for example)!
> node: don't log errors for services without methods

- pkg/auto/lights/action.go
- pkg/auto/lights/auto.go
- pkg/auto/lights/auto_test.go
- pkg/auto/lights/buttons.go
- pkg/auto/lights/config/root.go
- pkg/auto/lights/log.go
- pkg/auto/lights/logic.go
- pkg/auto/lights/logic_test.go
- pkg/auto/lights/patch.go
- pkg/auto/lights/patch_brightness_sensor.go
- pkg/auto/lights/patch_button.go
- pkg/auto/lights/patch_modes.go
- pkg/auto/lights/patch_occupancy_sensor.go
- pkg/auto/lights/state.go
- pkg/util/pull/pull.go
A collection of changes that improve the logging for the lighting automation.
Most of the changes are minor: remove duplicate fields, rename a type, etc. The big one is the rewriting of the logging system for the auto that's in 29cd077ad1c5f51443a2834d4505109225cbae9f which is the part that really needs a review.
I've attempted to keep the logic the same throughout, only changing logging lines and related bits (func args, etc). But there are a few minor changes that might cause issue later (assuming the tests missed them). The biggest one I can see is that the WriteState used to only record successful changes, now it also records failed changes. This happened in c3598c2c4be5a8bd17157be7c952dd285bf4f779 (I think).
I've deleted/refactored a couple of bits I noticed to make them more Go:
- …
> auto/lights: better logging

- example/config/vanti-ugs/ui-config.json
- ui/ops/src/composables/devices.js
- ui/ops/src/dynamic/widgets/pallet.js
- ui/ops/src/routes/devices/components/DeviceTable.vue
These changes were mostly about relaxing the subsystem filtering assumptions we were using when the device was a full page with sidebar nav. Now you can filter by subsystem if the condition isn't forced.
> ui/ops: allow the device table to be included in dashboard pages

- pkg/auto/lights/action.go
- pkg/auto/lights/auto_test.go
Before we used to return early when writing to the lights when the first error was encountered. Now we keep going, collecting errors as we go.
> auto/lights: write to all lights on error

- ui/ops/src/api/convpb.js
- ui/ops/src/api/sc/traits/air-temperature.js
- ui/ops/src/components/filter/ListChooser.vue
- ui/ops/src/components/filter/filterCtx.js
- ui/ops/src/components/filter/pageCtx.js
- ui/ops/src/components/ui-error/error.js
- ui/ops/src/routes/ops/notifications/NotificationsTable.vue
- ui/ops/src/routes/ops/overview/pageConfig.js
- ui/ops/src/stores/uiConfig.js
- ui/ops/src/thirdparty/panzoom/PanZoom.vue
- ui/ops/src/traits/airTemperature/airTemperature.js
- ui/ops/src/traits/light/light.js
- ui/ops/src/util/traits.js
Calling hasOwnProperty on an instance was already discouraged in favour of Object.prototype.hasOwnProperty. As that's a mouth full modern browsers also have Object.hasOwn to replace this.
> ui/ops: replace a.hasOwnProperty(b) with Object.hasOwn(a, b)

- pkg/driver/bacnet/config/traits.go
- pkg/driver/bacnet/merge/air_temperature.go
- pkg/driver/bacnet/merge/fan_speed.go
- pkg/driver/bacnet/merge/mode.go
- pkg/driver/bacnet/merge/poll.go
- pkg/driver/bacnet/merge/poll_test.go
> It seems updating the set point leads to errors being thrown in the frontend.. even when the temperature does actually get updated... eventually. I am looking at the BacNet driver, it seems the number of tries in the poll + test functionality is set to 5. Does this need changing to pull the tries from the config? Or was it hardcoded for a reason and 5 tries should be enough pointing a deeper issue with BacNet?
> driver/bacnet: add tries as a configurable field for update poll tests

- pkg/driver/bacnet/merge/emergency.go
- pkg/driver/bacnet/merge/emergency_test.go
Add an option on the bacnet alarm config to trigger an emergency if a value drops below a good ok value.
We already supported an equality comparison, this adds support for an equality comparison.
Also adds support for float values
> Add bacnet emergency lowerthan

- internal/router/loopback.go
- internal/router/loopback_test.go
The cause of the panic was proto.Merge not behaving as advertised when merging proto.Messages that have equivalent but != protoreflect.Descriptor instances, like we have on the gateway as we use protodesc and dynamicpb packages to create dynamic descriptors and messages.
The fix is to fall back to the slow path in these cases and round trip the merge via proto.Mershal/Unmarshal. proto.Merge is advertised to be equivalent to this anyway.
Fixes SC-1002
> router: fix panic when downloading devices from the gateway

- pkg/system/gateway/scan.go
Change the ServiceDescriptor used by the gateway to the one in protoregistry.GlobalFiles if it exists. This makes our dynamic services more consistent with assumptions in the proto package (proto.Equal, proto.Merge) which assume a message is described by a single service descriptor, this wasn't true before this change.
I've implemented the change in a way that avoids additional reflection calls on the remote node if we already know how to describe the service.
Fixes SC-1004
Fixes SC-1002 - #334 also fixes it more locally
> system/gateway: use local descriptors where possible

- pkg/history/pgxstore/schema.sql
- pkg/history/pgxstore/store.go
This change adjusts the queries and indexes used by the postgres history store to be ~10,000x more performant. In general the changes involved replacing AND clauses with inner selects in certain cases where indexes could not be used for either selection or sorting.
I assume the difference in performance is due to Postgres not being aware that the create_time col is also consistently ordered, just like the PK. The change to the query makes use of this fact to better optimise how the query is run using nested selects.
> history: fix performance issues with reading history pages

- demo/README.md
- demo/vanti-ugs/scripts/trust-ugs.sh
This should help when using the UI through a browser. Currently throws a certificate invalid page which isn't exactly purposeful for demos either. And when using the sc-bos demo as a backend to test site UIs, request don't even get through. So I thought I'd add a script for tooling purposes to trust these generated certificates.
Disclaimer, I have only tested this on MacOS. Feel free to add one for Windows too.
> demo/vanti-ugs: script to trust crts generated by docker on macOS

- pkg/auto/wordpress/job/air_quality.go
This is a hot fix to get prettier Co2 Levels displayed from WordPress.
> auto/wordpress: iaq rounding

- pkg/driver/steinel/hpd/poller.go
get a data update immediately when the driver starts instead of waiting for first timer elapse
> driver/steinel: update data when first starting driver

- internal/manage/devices/download.go
- internal/manage/devices/server.go
Add a timeout around each 'page'. Where page is a simple get for non-historical downloads and a list page request for historical downloads.
Fixes SC-1023
> devices: during download don't wait forever for devices to respond

- example/config/vanti-ugs/space-ui.json
- ui/space/package.json
- ui/space/src/components/CircularGauge.vue
- ui/space/src/components/StatusChip.vue
- ui/space/src/routes/components/AirQualityCard.vue
- ui/space/src/routes/components/airQuality.js
- ui/space/src/routes/home/HomePage.vue
- ui/space/src/routes/home/home.js
- ui/space/src/util/string.js
- ui/space/src/util/traits.js
- ui/space/src/util/types.js
- ui/yarn.lock
Also support controlling which widgets are shows via the ui config.
I expect a future commit will make the ui-config widgets more of a suggestion and then rely on the configured zone to know exactly what this space supports. But as the feature has been deprioritised that can wait.
> ui/space: add air quality widget

- cmd/tools/client-waste/main.go
- example/config/vanti-ugs/app.conf.json
- go.mod
- go.sum
- pkg/driver/mock/auto/waste.go
- pkg/driver/mock/driver.go
Closes SC-1005. Adds mock driver support for the waste trait, the config to enabled this at the UGS example and a test client for listing waste records. It relies on this PR -> https://github.com/smart-core-os/sc-golang/ and the go.mod currently references the unmerged PR in sc-golang, but this PR in sc-bos helps test the one in sc-golang
To test this, run the ugs example backend and then run the command `go run cmd/tools/client-waste/main.go --insecure-skip-verify=true --name=van/uk/brum/ugs/devices/waste` to see the waste events get listed and pulled as more are generated
> drivers/mock: add support for the waste trait

- pkg/auto/wordpress/job/occupancy.go
Make use of Occupancy trait's confidence value so we don't send bad counts to WordPress.
> auto/wordpress: make use of confidence measure in occupancy response

- ui/ops/src/composables/time.js
- ui/ops/src/dynamic/widgets/pallet.js
- ui/ops/src/traits/meter/ConsumptionCard.vue
- ui/ops/src/traits/meter/meter.js
This widget shows the meter consumption between two dates, where one of the dates can be `now`.
A few examples:
- Show usage for yesterday
- Show usage for this week so far
- Show total usage for last year
A few examples on a test dashboard I was using
Using this mark up
```html
<div class="d-flex ga-2 mt-4">
<consumption-card :name="totalDemandName" period="day" title="Consumption" width="14em" variant="tonal"/>
<consumption-card :name="totalGeneratedName" period="day" title="Generation" width="14em" variant="text" color="success"/>
<consumption-card :name="totalDemandName" period="month" width="14em" variant="flat" color="error"/>
<consumption-card :name="totalGeneratedName" period="year" title="Solar Panels" width="14em" variant="outlined"/>
</div>
<div class="d-flex ga-2 mt-4"> …
```
> ui/ops: add meter/ConsumptionCard widget

- pkg/task/service/retry.go
- pkg/task/service/service.go
For reasons I am yet to figure out, the delay became negative {"delay": "-2562047h47m16.854775808s"} which caused the driver to retry at a very fast rate see https://vanti.youtrack.cloud/issue/OCW-133/when-driver-applyConfig-fails-for-a-while-it-retries-very-rapidly
This just adds a simple guard against this behaviour
> service/retry: add min delay for retrying

- pkg/driver/bacnet/config/write.go
- pkg/driver/bacnet/write.go
Every project was copying the same code over for sorting, marshalling and writing the bacnet config, this just brings the shared code here to eliminate this duplication and to reinforce consistent structure and naming across projects. Most projects will be able to use this after wrangling their own point reports, but can still define their own writers if they need to for some reason.
This also adds the ability to add history configuration for a list of traits
> drivers/bacnet: add helper for config sorting, marshalling and writing

- ui/ops/src/components/AppMenu.vue
Remove wording for things you can't do (like creating devices) and rename Auto to Access Management
Now looks like this
> ui/ops: reorder and reword the main menu

- example/config/vanti-ugs/ui-config.json
- ui/ops/package.json
- ui/ops/src/composables/time.js
- ui/ops/src/dynamic/widgets/energy/EnergyHistoryCard.vue
- ui/ops/src/dynamic/widgets/energy/EnergyTooltip.vue
- ui/ops/src/dynamic/widgets/energy/PeriodChooserRows.vue
- ui/ops/src/dynamic/widgets/energy/chart.js
- ui/ops/src/dynamic/widgets/energy/consumption.js
- ui/ops/src/dynamic/widgets/energy/date.js
- ui/ops/src/dynamic/widgets/pallet.js
- ui/ops/src/style.scss
- ui/ops/src/traits/meter/ConsumptionCard.vue
- ui/ops/src/traits/meter/meter.js
- ui/yarn.lock
The EnergyHistoryCard is a widget that shows stacked energy usage for a number of sources, intended to break down (for example) a building by floors to give a broader overview of energy use where ancestry is known.
This change also updates the ConsumptionCard widget as additional time utils have been written that this component can make use of.
I've added the chart to a new dashboard page for the ugs example so it should be easy to test with.
**Known Issues/Additions**
1. The chart is a little jumpy as data is loaded into it. This could be solved with a loading indicator of some kind but I feel like that can be added as a future change
2. There's no way to download the data in the chart. I intend for this to download all meter data over the selected range, rather than just the consumption …
> ui/ops/energy: add EnergyHistoryCard widget

- example/config/vanti-ugs/ui-config.json
- ui/ops/package.json
- ui/ops/src/api/ui/waste.js
- ui/ops/src/composables/waste.js
- ui/ops/src/routes/ops/OpsNav.vue
- ui/ops/src/routes/ops/route.js
- ui/ops/src/routes/ops/waste/WasteTable.vue
- ui/ops/src/routes/ops/waste/route.js
- ui/yarn.lock
Adds a page under the ops section to view waste records. Functionality is MVP, just has to be able to view records at this point.
Not sure about the icon as it is not really just about recycling, could use mdi-basket-fill or possibly a trash can, but I thought that was too much like delete.
The vanti ugs example is already configured to generate mock waste records too
> ui/ops: add page to view waste records

- internal/account/convert.go
- internal/account/queries/queries.sql
- internal/account/queries/queries.sql.go
- internal/account/server.go
- internal/account/server_test.go
- internal/account/store.go
When ListRoles encounters a Role with an empty permissions list, an internal error is returned.
Expected behavior is to return the Role with an empty permissions list.
Also fix bug with incorrect error code being returned by CreateRole and UpdateRole when the supplied `display_name` for create/update conflicts with an existing role.
> SC-1056: Fix ListRoles error when Role has no permissions

- pkg/auto/exporthttp/job/job.go
I just noticed I was using the `energy` meter list for `water` reporting.
> auto/exporthttp: use correct meter list for water job

- internal/account/migrations/0002_multiple_scopes.sql
- internal/account/server_test.go
By the original design, a role can only be assigned to an account once. However, this prevents joining multiple scopes of the same role. This prevents us from migrating away from the Tenant API, which supports this use case.
Loosen the uniqueness constraint, so that only completely identical role assignments (same account, role & scope) are prohibited.
> SC-1059: allow multiple role assignments for same account & role

- ui/ops/src/composables/action.js
- ui/ops/src/composables/collection.js
These changes combine to fix the race we have in useCollection that causes rapid request changes to show old results.
The fix comes in the form of a new `useAction` utility that _correctly_ handles the request change vs async request race and converting the list part of useCollection to use this utility. Future changes will make use of `useAction` too, which is why it's been factored out.
While the refresh func isn't required for this fix, it is part of a wider change for which this fix has been extracted. The change was small enough that I thought it better to include it here than to create dependent PRs. Especially as the code changes once the actual fix lands.
Fixes SC-985
> ui/ops: fix useCollection race

- cmd/tools/test-exporthttp/main.go
- cmd/tools/test-exporthttp/sensors.go
- pkg/auto/exporthttp/auto.go
- pkg/auto/exporthttp/config/root.go
- pkg/auto/exporthttp/job/energy.go
- pkg/auto/exporthttp/job/job.go
- pkg/auto/exporthttp/job/occupancy.go
- pkg/auto/exporthttp/job/water.go
Since time intervals may keep resetting if the controllers are restarted, using cron schedules is a more reliable way to ensure "at least 1 execution per schedule". Intervals are reset multiple times before the subsequent execution schedule meaning the automation reporting is unreliable.
I have also buffered the job chan in case an execution takes longer than the smallest unit schedule interval - by executing the job in a go-routine and buffering the multiplexed job chan, we can ensure executions which are scheduled around the same time execute concurrently.
> auto/exporthttp: swap to cron schedules instead of time intervals

- cmd/tools/test-exporthttp/main.go
- pkg/auto/exporthttp/config/root.go
- pkg/auto/exporthttp/job/air_quality.go
- pkg/auto/exporthttp/job/energy.go
- pkg/auto/exporthttp/job/job.go
- pkg/auto/exporthttp/job/occupancy.go
- pkg/auto/exporthttp/job/temperature.go
- pkg/auto/exporthttp/job/water.go
Since 5s timeout per sensor / meter device is too short in production deployments, I have made this configurable from the JSON configuration.
> auto/exporthttp: get ctx timeout from config

- pkg/util/pull/pull.go
The old logic was overly complicated with the aim of printing the now succeeding message as soon as we could, but had the drawback that it'd get it wrong frequently. This was compounded by the success timer counting the backoff delay too so as attempts increased it became more likely to incorrectly report success.
Aside from the logging, false success messages were also resetting the backoff causing excess churn.
The new code is much simpler and also more reliable at the cost of delaying the success log message, which we can live with.
> util/pull: reduce incorrect "pull now succeeding" messages

- pkg/auto/bms/config/root.go
- pkg/auto/bms/logic.go
- pkg/auto/bms/logic_test.go
The schedule works either independently or with the occupancy sensors. Without sensors the occupancy mode will be set to on when within the schedule, and off otherwise. When sensors exist, occupied mode is only ever set to on within the schedule using the normal occupancy sensor logic.
I've added tests for all the occupancy cases, both existing and schedule based, just to make sure I didn't introduce any regressions here.
> auto/bms: allow occupancy to be changed on a schedule

- cmd/tools/dbadd-alerts/main.go
- cmd/tools/list-occupancy-history/main.go
- cmd/tools/proxy-test/main.go
- cmd/tools/pull-enter-leave/main.go
- cmd/tools/sample-tenant/main.go
- internal/router/stream_test.go
- internal/util/grpc/reflectionapi/server_test.go
- pkg/app/servers_test.go
- pkg/auth/policy/interceptor_test.go
- pkg/auto/azureiot/traits.go
- pkg/driver/proxy/config/root.go
- pkg/driver/proxy/driver.go
- pkg/hub/pull.go
- pkg/manage/enrollment/server.go
- pkg/node/remote.go
- pkg/node/remote_test.go
- pkg/system/gateway/internal/test/gateway_test.go
- pkg/system/gateway/scan.go
- pkg/system/hub/bolthub/server.go
- pkg/system/hub/pgxhub/server.go
- pkg/system/hub/remote/enroll.go
- pkg/system/hub/remote/inspect.go
- pkg/util/client/client.go
- pkg/util/client/wait.go
grpc.Dial/Context has been deprecated, as have options grpc.WithBlock and friends.
Most of the work here is about also removing the grpc.WithBlock and related options which aren't usable with NewClient.
There were some logic changes needed in the hub packages, but I don't think they'll have any noticeable effects on our deployments. Mostly making sure we perform at least one RPC before assuming we have the server cert captured.
The surprising thing was in node/remote.go which required a Connect call to build the resolver before the address could be updated. Without this the code would panic.
Finally, it appears that NewClient doesn't accept an empty target string, where Dial and DialContext did, at least in the case where the Dialler was replaced. In these cases I've used a localhost …
> all: replace grpc.Dial/Context calls with grpc.NewClient

- pkg/history/pgxstore/schema.sql
The index was never used and consumed a large amount of disk space.
> history: remove unused pgx index

- pkg/auto/exporthttp/auto.go
- pkg/auto/exporthttp/job/energy.go
- pkg/auto/exporthttp/job/job.go
- pkg/auto/exporthttp/job/meter.go
- pkg/auto/exporthttp/job/meter_test.go
- pkg/auto/exporthttp/job/water.go
This makes use of this fix https://github.com/vanti-dev/sc-bos/commit/bb723ae88593cc508f1886597484fc7fc979a8a0 which allows clients to calculate consumption between 2 timestamps without paginating through _**every meter history result between those 2 timestamps**_.
I have also added a fix because I don't trust
```
for {
select {
case <-time.After(...):
...
}
}
```
won't execute case statements more than once when receiving from a chan dictated by a cron schedule.
> auto/exporthttp: use order by and page size = 1 to reduce the amount of pagination in ListMeterHistory calls to calculate consumption in meters

- pkg/auto/history/airqualitysensor.go
- pkg/auto/history/airtemperature.go
- pkg/auto/history/collect.go
- pkg/auto/history/config/root.go
- pkg/auto/history/dedupe.go
- pkg/auto/history/electric.go
- pkg/auto/history/factory.go
- pkg/auto/history/factory_test.go
- pkg/auto/history/meter.go
- pkg/auto/history/occupancysensor.go
- pkg/auto/history/status.go
- pkg/util/jsontypes/schedule.go
The default behaviour will be as before: without a cron schedule for the history automation, the pull.Fetcher will determine whether polling or pull operations are used to fetch changes from a device trait.
However, if a cron schedule is provided, the history automation will use a poll cycle to fetch values on a given schedule, and will ignore duplicate consecutive changes to device traits.
This is effort taken to reduce the storage required for a history automation.
> auto/history: refactor to allow pollOnSchedule lifecycle defined by a cron schedule in config

- ui/ops/src/routes/login/LocalLogin.vue
One of the facilities managers on-site complained she couldn't view her Ops UI password when entering it for the first time (received on one machine, and entered via a keyboard halfway across the room).
I am hoping this PR shows we are responding to their complaints / suggestions.
https://github.com/user-attachments/assets/339c5e98-7c60-4545-8a7a-52f29fc2823f
> ui/ops: add a button to show password in browser when clicked

- pkg/auto/history/airqualitysensor.go
- pkg/auto/history/airtemperature.go
- pkg/auto/history/collect.go
- pkg/auto/history/config/root.go
- pkg/auto/history/dedupe.go
- pkg/auto/history/electric.go
- pkg/auto/history/factory.go
- pkg/auto/history/factory_test.go
- pkg/auto/history/meter.go
- pkg/auto/history/occupancysensor.go
- pkg/auto/history/status.go
- pkg/history/memstore/store.go
- pkg/history/memstore/store_test.go
- pkg/history/store.go
- pkg/util/jsontypes/schedule.go
This is a new feature where a schedule can be provided to a history automation.
The default behaviour will be as before: without a cron schedule for the history automation, the pull.Fetcher will determine whether polling or pull operations are used to fetch changes from a device trait. However, if a cron schedule is provided, the history automation will use a poll lifecycle to fetch values on a given schedule, and will ignore duplicate consecutive changes to device traits. This is effort taken to reduce the storage required for a history automation.
Also, fixes a condition where if payloads are contain structs such as protobuf structs, the lack of a in-memory guard throws a lot of race conditions between slice.Append and slice.Slice calls.
See …
> auto/history: refactor to allow pollOnSchedule lifecycle defined by a cron schedule in config and fix history/memory store for tests

- pkg/auto/lights/auto.go
- pkg/auto/lights/auto_test.go
- pkg/auto/lights/logic_test.go
This includes a bunch of changes that might help us diagnose flaky tests:
1. Increase the timeout for state changes by an order of magnitude
2. Replace use of emitter with a blocking call to reduce async-iness
3. Hold a lock when signalling the next call should return an error
4. Turn on logging for when the above inevitably fails to fix the issue
> auto/lights: hope to make the test more reliable

- pkg/driver/bacnet/merge/light.go
- pkg/driver/bacnet/merge/trait.go
Although some BacNet light points may support granular brightness intensity levels, I have opted to stick to scenes only for now as these are usually paired with interactions with the PIRs which breaks or requires additional logic involving timeouts and such when setting granular intensities.
> driver/bacnet: support light trait

- pkg/task/poll_test.go
There is a possibility the ctx provided to Intermittent.Attach() is cancelled before the goroutine that is listening for this cancellation has acquired the mutex lock. This means for short-running tasks, the underlying poll func is called more times than expected.
See: https://github.com/vanti-dev/sc-bos/actions/runs/14968760102/job/42044643884#step:5:207
> pkg/task: explictly signal stop has been called due to slow mtx acquisition

- pkg/driver/bacnet/merge/occupancy.go
- pkg/driver/bacnet/merge/trait.go
I have implemented the most basic support for occupancy based on the MLS documentation. This is sufficient for our first deployment of this driver. However, more complex config options may be required for other BacNet implementations e.g. a `flipBool` field for when true -> unoccupied or when the sensor provides peopleCount points (where MLS doesn't).
> driver/bacnet: support occupancy trait

- example/config/vanti-ugs/ui-config.json
- ui/ops/src/dynamic/layout/pallet.js
- ui/ops/src/routes/ops/nav.js
- ui/ops/src/routes/ops/waste/WasteTable.vue
This PR allows static ops pages like security or air quality to be placed anywhere in the ops nav via the existing pages config.
The UGS example has been updated to place them into the subsystems container.
There are now two ways to configure the inclusion of the static pages in the ops nav:
1. Use the `features` object to explicitly allow only the pages you want
2. _New_: Remove config for the static pages or add a `page: false` to the ops config object where no specific config is needed. See the UGS example for details.
The only page not configurable via this mechanism is the Notifications page because of the badge number. I'd like this to move into the main toolbar at some point so won't be configuring it here.
> ui/ops/ops: make all ops pages configurable via pages config

- pkg/auto/azureiot/traits.go
- pkg/auto/export/source/bacnet.go
- pkg/auto/export/source/mqtt.go
- pkg/auto/meteremail/auto.go
- pkg/auto/notificationsemail/auto.go
- pkg/auto/occupancyemail/auto.go
- pkg/auto/resetenterleave/auto.go
- pkg/auto/statusemail/auto.go
- pkg/auto/udmi/udmi.go
- pkg/system/gateway/factory.go
This has been deprecated for a while now, lets get rid of it.
> all: remove use of deprecated Node.Client

- pkg/driver/helvarnet/pir.go
Confidence of 0 are filtered by some automations. This guarantees the occupancy state is used during exports.
> driver/helvanet: set confidence of pir sensors to 1 all the time

- ui/ops/src/routes/ops/emergency-lighting/EmergencyLighting.vue
fixes this issue which was happening on the test emergency lighting page
> ui/ops: fix broken emergency lighting test click

- pkg/gen/dali.pb.go
- proto/dali.proto
- ui/ui-gen/proto/dali_grpc_web_pb.js
- ui/ui-gen/proto/dali_pb.d.ts
- ui/ui-gen/proto/dali_pb.js
we can query the Helvarnet devices to tell us the last time the test was run, add support for this in the DALI trait.
> proto/dali: add start & end time to test result

- pkg/driver/helvarnet/command.go
- pkg/driver/helvarnet/config/root.go
- pkg/driver/helvarnet/driver.go
- pkg/driver/helvarnet/light.go
adds support to the Helvarnet driver to run emergency light tests and get the results. Uses the DALI proto API, while Helvarnet itself is not DALI, it is basically just a wrapper around DALI lights.
Tested on invoking function tests and querying the results. Testing duration tests is a bit more invloved, I will need to arrange this but the logic is the same.
At the moment this does not use the GetTestTime commands, see the todo, support for these will follow once I have added it into the DALI proto
> driver/helvarnet: add support for emergency light tests

- pkg/gentrait/devicespb/collection.go
- pkg/node/metadata.go
- pkg/node/node.go
- pkg/node/node_test.go
I've added a list of metadata that gets collapsed to form the announced metadata, both on add and undo. This increases the memory footprint, but not that significantly.
Unfortunately the change was made on top of existing work and other PRs. Hopefully it can be merged after those, if desired I can rework all the PRs to put this one first, though that's not insignificant work.
> node: fix undoing an announcement would delete the device

- demo/vanti-ugs/system.conf.json
- example/config/vanti-ugs/system.conf.json
The system conf for the demo should match the example UGS as much as possible, as we use the app and ops ui config from this example.
> demo,example/ugs: make system config consistent

- pkg/auto/statusalerts/statusalerts.go
- pkg/auto/statusemail/auto.go
- pkg/auto/udmi/udmi.go
I cannot find any references to where the top level message struct name needs to be included in the fieldmask path.
I am pretty sure the string path shouldn't include the top level message name and have found the documented example doesn't either. Although, the documentation does mislead us by suggesting the top level message name is part of the field mask.
// As an example, consider the following message declarations:
//
//     message Profile {
//       User user = 1;
//       Photo photo = 2;
//     }
//     message User {
//       string display_name = 1;
//       string address = 2;
//     }
//
// In proto a field mask for `Profile` may look as such:
//
//     mask {
//       paths: "user.display_name"
//       paths: "photo"
//     }
Where it misleads us:
// `FieldMask` represents a …
> auto/statusemail;auto/statusalerts;auto/udmi: change readPaths top level message validation type to *gen.Device

- pkg/driver/helvarnet/config/root.go
- pkg/driver/helvarnet/driver.go
- pkg/driver/helvarnet/light.go
use the new emergency light trait instead of dali in Helvarnet driver .
this commit on it's own will mean the Emergency Light page will no longer be able to invoke tests for this driver as that page still uses DALI. Plan is to update that page next to invoke tests using `emergency_light` and then update downstream projects. I will leave the `lighting_test` changes until last
> driver/helvarnet: use emergency light trait

- pkg/gentrait/soundsensorpb/model_server.go
- pkg/gentrait/soundsensorpb/model_server_test.go
Server method implementations had the wrong name so this type actually didn't do anything at all when used as a SoundSensorApiServer.
> soundsensorpb: fix ModelServer not working at all

- pkg/driver/hikcentral/config/root.go
Upgrading the sc-bos version in Area Controllers where the HikCentral driver is used on site causes panics due to missing the `settings` field. Rather than changing the JSON config, I opted to default the durations in the `settings` field if this is missing in JSON config.
> driver/hikcentral: set default durations for settings in config

- ui/ops/src/traits/transport/transport.js
The aim is to get more rows populated in the transport card.
> ui/ops: fix rendering of transport card trait fields

- example/config/vanti-ugs/ui-config.json
- ui/ops/src/dynamic/widgets/environmental/EnvironmentalCard.vue
In some dashboards the 'Environmental' title is not the best choice for this card.
Add a prop title, defaulting to 'Environmental', to customise the title.
If the title is set to an empty string, the title is not displayed at all (so there's no blank space at the top of the card).
To demonstrate the new functionality, use it in the UGS example.
> ui/ops: allow customising or removing the title in EnvironmentalCard

- ui/ops/src/traits/electricDemand/ElectricDemandCell.vue
[SCB-1205](https://vanti.youtrack.cloud/issue/SCB-1205) Show current in inline widget if power unavailable
> ui/ops: show current instead if power is unavailable

- example/config/vanti-ugs/ui-config.json
- ui/ops/src/dynamic/widgets/environmental/AirQualityHistoryCard.vue
- ui/ops/src/dynamic/widgets/environmental/AirQualityHistoryChart.vue
- ui/ops/src/dynamic/widgets/environmental/airQuality.js
Allow an array of sources to be specified for the AirQualityHistoryCard widget. All will be shown by default. Series can be deselected from the options menu to hide them.
The download button will only download data for series visible on the chart.
> ui/ops: support multiple devices in AirQualityHistoryCard / AirQualityHistoryChart
